name: navr_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  flutter_svg: ^2.1.0
  auto_size_text: ^3.0.0
  gradient_borders: ^1.0.1
  country_flags: ^3.2.0
  easy_localization: ^3.0.7+1
  shared_preferences: ^2.5.3
  carousel_slider: ^5.0.0
  fast_cached_network_image: ^1.3.3+5
  flutter_rating_bar: ^4.0.1
  zoom_tap_animation: ^1.1.0
  image_picker: ^1.1.2
  # 
  bloc: ^9.0.0
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  skeletonizer: ^2.0.1
  google_sign_in_ios: ^5.9.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0
  freezed: ^3.0.6
  json_annotation: ^4.9.0
  flutter_html: ^3.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/nav/
    - assets/translations/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Italic.ttf
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: KleeOne
      fonts:
        - asset: assets/fonts/KleeOne-SemiBold.ttf
    - family: Iconmoon
      fonts:
        - asset: assets/fonts/icomoon.woff
